# Generated by Django 2.1.7 on 2019-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShows', '0002_shows_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
